# Generated by Django 4.1 on 2022-08-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_artesania_descripcion_alter_artesania_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artesania',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
